# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\ocsen\PycharmProjects\Szakdoga\pyqt lapok\homewinuj.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from ques1 import *
from profilwin import *
from savename import *
from savewin import *

class Ui_homewin(object):
    def setupUi(self, homewin):
        homewin.setObjectName("homewin")
        homewin.setEnabled(True)
        homewin.resize(1024, 720)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(homewin.sizePolicy().hasHeightForWidth())
        homewin.setSizePolicy(sizePolicy)
        homewin.setMinimumSize(QtCore.QSize(1024, 720))
        homewin.setMaximumSize(QtCore.QSize(1024, 720))
        self.centralwidget = QtWidgets.QWidget(homewin)
        self.centralwidget.setObjectName("centralwidget")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(0, 0, 1024, 720))
        self.label_5.setMinimumSize(QtCore.QSize(1024, 720))
        self.label_5.setMaximumSize(QtCore.QSize(1024, 720))
        self.label_5.setMouseTracking(False)
        self.label_5.setTabletTracking(False)
        self.label_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("képek/fomenu.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(330, 80, 361, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.profilbutton = QtWidgets.QPushButton(self.centralwidget)
        self.profilbutton.setGeometry(QtCore.QRect(340, 320, 340, 51))
        self.profilbutton.setStyleSheet("QPushButton{\n"
                                        "    background: rgb(255, 255, 255);\n"
                                        "    border: 2px solid rgb(180, 180, 180);\n"
                                        "    border-radius: 20px;\n"
                                        "}")
        self.profilbutton.setObjectName("profilbutton")
        self.mentesbutton = QtWidgets.QPushButton(self.centralwidget)
        self.mentesbutton.setGeometry(QtCore.QRect(280, 440, 440, 51))
        self.mentesbutton.setStyleSheet("QPushButton{\n"
                                        "    background: rgb(255, 255, 255);\n"
                                        "    border: 2px solid rgb(180, 180, 180);\n"
                                          "    border-radius: 20px;\n"
                                        "}")
        self.mentesbutton.setObjectName("mentesbutton")
        self.B1 = QtWidgets.QPushButton(self.centralwidget)
        self.B1.setGeometry(QtCore.QRect(360, 260, 290, 51))
        self.B1.setStyleSheet("QPushButton{\n"
                                "    background: rgb(255, 255, 255);\n"
                                "    border: 2px solid rgb(180, 180, 180);\n"
                                "    border-radius: 20px;\n"
                                "}")
        self.B1.setObjectName("B1")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(390, 200, 83, 51))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.T1 = QtWidgets.QLineEdit(self.centralwidget)
        self.T1.setGeometry(QtCore.QRect(480, 200, 150, 51))
        self.T1.setObjectName("T1")
        self.T1.setStyleSheet("QLineEdit{\n"
                             "    background: rgb(255, 255, 255);\n"
                             "    border: 2px solid rgb(180, 180, 180);\n"
                             "    border-radius: 20px;\n"
                            "}"
                              "QLineEdit:focus{\n"
                                        "border: 2px solid rgb(0, 0, 0);\n"
                                        "}"
                              )
        self.beallitasbutton = QtWidgets.QPushButton(self.centralwidget)
        self.beallitasbutton.setGeometry(QtCore.QRect(310, 380, 390, 51))
        self.beallitasbutton.setStyleSheet("QPushButton{\n"
                                            "    background: rgb(255, 255, 255);\n"
                                            "    border: 2px solid rgb(180, 180, 180);\n"
                                            "    border-radius: 20px;\n"
                                            "}")
        self.beallitasbutton.setObjectName("beallitasbutton")
        homewin.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(homewin)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 21))
        self.menubar.setObjectName("menubar")
        homewin.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(homewin)
        self.statusbar.setObjectName("statusbar")
        homewin.setStatusBar(self.statusbar)

        self.retranslateUi(homewin)
        QtCore.QMetaObject.connectSlotsByName(homewin)

        self.beallitasbutton.clicked.connect(self.show_popup)

    def retranslateUi(self, homewin):
        _translate = QtCore.QCoreApplication.translate
        homewin.setWindowTitle(_translate("homewin", "Játékos matematikai gyakorlóprogram"))
        self.label_6.setText(_translate("homewin", "Játékos matematikai gyakorlóprogram"))
        self.profilbutton.setText(_translate("homewin", "Profil létrehozása"))
        self.mentesbutton.setText(_translate("homewin", "Mentések betöltése"))
        self.B1.setText(_translate("homewin", "Játék indítása"))
        self.label_9.setText(_translate("homewin", "Becenév :"))
        self.beallitasbutton.setText(_translate("homewin", "Beállítások"))
        self.B1.clicked.connect(self.opques)
        self.B1.clicked.connect(homewin.hide)
        self.profilbutton.clicked.connect(self.opprofil)
        self.profilbutton.clicked.connect(homewin.hide)
        self.mentesbutton.clicked.connect(self.opsavename)
        self.mentesbutton.clicked.connect(homewin.hide)


    def show_popup(self):
        msg = QMessageBox()
        msg.setWindowTitle("Beállítások")
        msg.setText(
            "A játék használatához 100-as nagyítás szükséges!")
        msg.setIcon(QMessageBox.Information)
        x = msg.exec_()

    def opsavename(self):
        self.savename = QtWidgets.QMainWindow()
        self.ui = Ui_savename()
        self.ui.setupUi(self.savename, homewin)
        self.savename.show()

    def opprofil(self):
        self.profilwin = QtWidgets.QMainWindow()
        self.ui = Ui_profilwin()
        self.ui.setupUi(self.profilwin, homewin)
        self.profilwin.show()

    def opques(self):
        self.S1 = self.T1.text()
        self.queswin = QtWidgets.QMainWindow()
        self.ui = Ui_ques1(self.S1)
        self.ui.setupUi(self.queswin)
        self.queswin.show()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    homewin = QtWidgets.QMainWindow()
    ui = Ui_homewin()
    ui.setupUi(homewin)
    homewin.show()
    sys.exit(app.exec_())
