# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\ocsen\PycharmProjects\Szakdoga\pyqt lapok\kincses.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from PyQt5.QtCore import *
import sys
from homewin import *

class Ui_kincses(object):
    def setupUi(self, kincses):

        kincses.setObjectName("kincses")
        kincses.resize(1024, 720)
        kincses.setMinimumSize(QtCore.QSize(1024, 720))
        kincses.setMaximumSize(QtCore.QSize(1024, 720))
        self.centralwidget = QtWidgets.QWidget(kincses)
        self.centralwidget.setObjectName("centralwidget")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(0, 0, 1024, 720))
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("képek/kincses.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.button = QtWidgets.QPushButton(self.centralwidget)
        self.button.setGeometry(QtCore.QRect(30, 30, 91, 31))
        self.button.setObjectName("button")
        self.button.setStyleSheet("QPushButton{\n"
                                           "    background: rgb(255, 255, 255);\n"
                                           "    border: 2px solid rgb(180, 180, 180);\n"
                                           "    border-radius: 20px;\n"
                                           "}")
        self.B1 = QtWidgets.QPushButton(self.centralwidget)
        self.B1.setStyleSheet("QPushButton{\n"
                                           "    background: rgb(255, 255, 255);\n"
                                           "    border: 2px solid rgb(180, 180, 180);\n"
                                           "    border-radius: 20px;\n"
                                           "}")
        self.B1.setGeometry(QtCore.QRect(440, 540, 131, 41))

        font = QtGui.QFont()
        font.setPointSize(14)
        self.B1.setFont(font)
        self.B1.setObjectName("B1")
        kincses.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(kincses)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 21))
        self.menubar.setObjectName("menubar")
        kincses.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(kincses)
        self.statusbar.setObjectName("statusbar")
        kincses.setStatusBar(self.statusbar)

        self.retranslateUi(kincses)
        QtCore.QMetaObject.connectSlotsByName(kincses)

        self.button.clicked.connect(self.show_popup)

    def retranslateUi(self, kincses):
        _translate = QtCore.QCoreApplication.translate
        kincses.setWindowTitle(_translate("kincses", "Játékos matematikai gyakorlóprogram"))
        self.button.setText(_translate("kincses", "?"))
        self.B1.setText(_translate("kincses", "Játék Vége"))
        self.B1.clicked.connect(self.opques)
        self.B1.clicked.connect(kincses.close)



    def show_popup(self):
        msg = QMessageBox()
        msg.setWindowTitle("Jutalom a játék teljesítéséért!")
        msg.setText("A kulcs egy kinccsel teli kamrát nyitott!")
        msg.setIcon(QMessageBox.Information)

        x = msg.exec_()

    def opques(self):
        self.queswin = QtWidgets.QMainWindow()
        self.ui = Ui_kincses()
        self.ui.setupUi(self.queswin)
        self.queswin.show()
        self.T1.setEnabled(False)
        self.T2.setEnabled(False)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    kincses = QtWidgets.QMainWindow()
    ui = Ui_kincses()
    ui.setupUi(kincses)
    kincses.show()
    sys.exit(app.exec_())