# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\ocsen\PycharmProjects\Szakdoga\pyqt lapok\profilwin.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from PyQt5.QtCore import *
import sys
from homewin import *

class Ui_profilwin(object):
    def setupUi(self, profilwin, homewin):
        self.homewin = homewin
        profilwin.setObjectName("profilwin")
        profilwin.setEnabled(True)
        profilwin.resize(1024, 720)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(profilwin.sizePolicy().hasHeightForWidth())
        profilwin.setSizePolicy(sizePolicy)
        profilwin.setMinimumSize(QtCore.QSize(1024, 720))
        profilwin.setMaximumSize(QtCore.QSize(1024, 720))
        self.centralwidget = QtWidgets.QWidget(profilwin)
        self.centralwidget.setObjectName("centralwidget")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(0, 0, 1024, 720))
        self.label_5.setMinimumSize(QtCore.QSize(1024, 720))
        self.label_5.setMaximumSize(QtCore.QSize(1024, 720))
        self.label_5.setMouseTracking(False)
        self.label_5.setTabletTracking(False)
        self.label_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("képek/fomenu.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(330, 80, 361, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(430, 160, 151, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(110, 240, 100, 100))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("képek/default-avatar-icon-of-social-media-user-vector.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(230, 240, 45, 45))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(230, 290, 45, 45))
        self.label_3.setObjectName("label_3")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(290, 240, 100, 45))
        self.lineEdit.setStyleSheet("QLineEdit{\n"
                                      "    background: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(180, 180, 180);\n"
"    border-radius: 20px;\n"
"}"
                                    "QLineEdit:focus{\n"
                                    "border: 2px solid rgb(0, 0, 0);\n"
                                    "}"
                                    )
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(290, 290, 100, 45))
        self.lineEdit_2.setStyleSheet("QLineEdit{\n"
                              "    background: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(180, 180, 180);\n"
"    border-radius: 20px;\n"
"}"
                                      "QLineEdit:focus{\n"
                                      "border: 2px solid rgb(0, 0, 0);\n"
                                      "}"
                                      )
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(650, 240, 160, 45))
        self.label_4.setObjectName("label_4")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(830, 240, 100, 100))
        self.label_8.setText("")
        self.label_8.setPixmap(QtGui.QPixmap("képek/kitűző.png"))
        self.label_8.setScaledContents(True)
        self.label_8.setObjectName("label_8")
        self.kituzobutton = QtWidgets.QPushButton(self.centralwidget)
        self.kituzobutton.setGeometry(QtCore.QRect(650, 290, 160, 45))
        self.kituzobutton.setStyleSheet("QPushButton{\n"
                                      "    background: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(180, 180, 180);\n"
"    border-radius: 20px;\n"
"}")
        self.kituzobutton.setObjectName("kituzobutton")
        self.visszabutton = QtWidgets.QPushButton(self.centralwidget)
        self.visszabutton.setGeometry(QtCore.QRect(410, 430, 160, 45))
        self.visszabutton.setStyleSheet("QPushButton{\n"
                                        "    background: rgb(255, 255, 255);\n"
"    border: 2px solid rgb(180, 180, 180);\n"
"    border-radius: 20px;\n"
"}"
"}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("képek/visszanyil.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.visszabutton.setIcon(icon)
        self.visszabutton.setIconSize(QtCore.QSize(25, 25))
        self.visszabutton.setCheckable(False)
        self.visszabutton.setAutoDefault(False)
        self.visszabutton.setDefault(False)
        self.visszabutton.setFlat(False)
        self.visszabutton.setObjectName("visszabutton")
        profilwin.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(profilwin)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 21))
        self.menubar.setObjectName("menubar")
        profilwin.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(profilwin)
        self.statusbar.setObjectName("statusbar")
        profilwin.setStatusBar(self.statusbar)

        self.retranslateUi(profilwin)
        QtCore.QMetaObject.connectSlotsByName(profilwin)

        self.kituzobutton.clicked.connect(self.show_popup)

    def retranslateUi(self, profilwin):
        _translate = QtCore.QCoreApplication.translate
        profilwin.setWindowTitle(_translate("profilwin", "Játékos matematikai gyakorlóprogram"))
        self.label_6.setText(_translate("profilwin", "Játékos matematikai gyakorlóprogram"))
        self.label_7.setText(_translate("profilwin", "<html><head/><body><p><span style=\" font-size:14pt;\">Profil létrehozása</span></p></body></html>"))
        self.label_2.setText(_translate("profilwin", "<html><head/><body><p><span style=\" font-size:12pt;\">Név:</span></p></body></html>"))
        self.label_3.setText(_translate("profilwin", "<html><head/><body><p><span style=\" font-size:12pt;\">Kor:</span></p></body></html>"))
        self.label_4.setText(_translate("profilwin", "<html><head/><body><p><span style=\" font-size:12pt;\">Megszerezhető kitűző:</span></p></body></html>"))
        self.kituzobutton.setText(_translate("profilwin", "?"))
        self.visszabutton.setText(_translate("profilwin", "Vissza a főmenübe"))
        self.visszabutton.clicked.connect(self.ophomewin)
        self.visszabutton.clicked.connect(profilwin.close)

    def show_popup(self):
        msg = QMessageBox()
        msg.setWindowTitle("Kitűző ismertető")
        msg.setText("Minden egyes pálya teljesítése után kitűzővel leszel gazdagabb!")
        msg.setIcon(QMessageBox.Information)

        x = msg.exec_()

    def ophomewin(self):
        self.homewin.show()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    profilwin = QtWidgets.QMainWindow()
    ui = Ui_profilwin()
    ui.setupUi(profilwin)
    profilwin.show()
    sys.exit(app.exec_())
