# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\ocsen\Desktop\szakdoga pyqt lapok\resultwin4.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from PyQt5.QtCore import *
import sys
from ques41 import *
import json
class Ui_resultwin4(QtWidgets.QWidget):
    def __init__(self, name, count, total):
        super().__init__()
        self.name = name
        self.count = count
        self.total = total
        self.S1 = str(self.count // 60)
        self.S2 = str(self.count % 60)
        self.S3 = self.S1 + ":" + self.S2
    def setupUi(self, resultwin4):
        resultwin4.setObjectName("resultwin4")
        resultwin4.resize(1024, 720)
        resultwin4.setMinimumSize(QtCore.QSize(1024, 720))
        resultwin4.setMaximumSize(QtCore.QSize(1024, 720))
        self.centralwidget = QtWidgets.QWidget(resultwin4)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(0, -10, 1024, 720))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("képek/hegyvidek.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.formLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.formLayoutWidget.setGeometry(QtCore.QRect(350, 270, 301, 91))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_4 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit.setStyleSheet("QLineEdit{\n"
                              "    background: rgb(0, 100, 188);\n"
                              "    border: 2px solid rgb(0, 79, 149);\n"
                              "    border-radius: 10px;\n"
                              "}")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.lineEdit_2.setStyleSheet("QLineEdit{\n"
                              "    background: rgb(0, 100, 188);\n"
                              "    border: 2px solid rgb(0, 79, 149);\n"
                              "    border-radius: 10px;\n"
                              "}")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.lineEdit_2)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.lineEdit_3.setStyleSheet("QLineEdit{\n"
                              "    background: rgb(0, 100, 188);\n"
                              "    border: 2px solid rgb(0, 79, 149);\n"
                              "    border-radius: 10px;\n"
                              "}")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.lineEdit_3)
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(410, 200, 191, 41))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.B1 = QtWidgets.QPushButton(self.centralwidget)
        self.B1.setGeometry(QtCore.QRect(350, 460, 301, 51))
        self.B1.setObjectName("B1")
        self.B1.setStyleSheet("QPushButton{\n"
                              "    background: rgb(0, 100, 188);\n"
                              "    border: 2px solid rgb(0, 79, 149);\n"
                              "    border-radius: 10px;\n"
                              "}")
        self.button = QtWidgets.QPushButton(self.centralwidget)
        self.button.setGeometry(QtCore.QRect(450, 380, 91, 51))
        self.button.setObjectName("button")
        self.button.setStyleSheet("QPushButton{\n"
                              "    background: rgb(0, 100, 188);\n"
                              "    border: 2px solid rgb(0, 79, 149);\n"
                              "    border-radius: 10px;\n"
                              "}")
        resultwin4.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(resultwin4)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 21))
        self.menubar.setObjectName("menubar")
        self.mentesgomb = QtWidgets.QPushButton(self.centralwidget)
        self.mentesgomb.setGeometry(QtCore.QRect(370, 530, 261, 41))
        self.mentesgomb.setStyleSheet("QPushButton{\n"
                              "    background: rgb(0, 100, 188);\n"
                              "    border: 2px solid rgb(0, 79, 149);\n"
                              "    border-radius: 10px;\n"
                              "}")
        self.mentesgomb.setObjectName("mentesgomb")
        resultwin4.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(resultwin4)
        self.statusbar.setObjectName("statusbar")
        resultwin4.setStatusBar(self.statusbar)

        self.retranslateUi(resultwin4)
        QtCore.QMetaObject.connectSlotsByName(resultwin4)

        self.button.clicked.connect(self.show_popup)

    def retranslateUi(self, resultwin4):
        _translate = QtCore.QCoreApplication.translate
        resultwin4.setWindowTitle(_translate("resultwin4", "Játékos matematikai gyakorlóprogram"))
        self.label_2.setText(_translate("resultwin4", "Becenév: "))
        self.label_3.setText(_translate("resultwin4", "Hátralévő idő:"))
        self.label_4.setText(_translate("resultwin4", "Szerzett pontszám:"))
        self.label_5.setText(_translate("resultwin4", "Hegyvidék | Eredmény"))
        self.B1.setText(_translate("resultwin4", "Tovább"))
        self.button.setText(_translate("resultwin4", "?"))
        self.mentesgomb.setText(_translate("resultwin", "Mentés"))
        self.lineEdit.setText(str(self.name))
        self.lineEdit_2.setText(str(self.S3))
        self.lineEdit_3.setText(str(self.total))
        self.B1.clicked.connect(self.opques)
        self.B1.clicked.connect(resultwin4.close)
        self.mentesgomb.clicked.connect(self.json)

    def readjson(self):
        file_path = "mentesek.json"

        try:
            with open(file_path, mode="r", encoding="utf-8") as json_file:
                return json.load(json_file)
        except Exception as e:
            return []

    def find_in_list(self, lst):
        return [x for x in lst if x["becenev"] == self.name]

    def json(self):
        data = {
            "becenev": self.name,
            "elert pontszam": self.total,
            "teljesitett palya": "hegyvidek"
        }

        lst = self.readjson()
        print(lst)
        players = self.find_in_list(lst)
        if len(players) > 0:
            players[0]["elert pontszam"] = self.total
            players[0]["teljesitett palya"] = "hegyvidek"
        else:
            lst.append(data)

        file_path = "mentesek.json"

        try:
            with open(file_path, mode="w", encoding='utf-8') as json_file:
                json.dump(lst, json_file, indent=4)
            QMessageBox.information(self, "Sikeres mentés!",
                                    "Sikeresen elmentetted az előrehaladásod! A főmenüben a mentések betöltése nevezetű gombnál egyből ide tudsz ugrani és innen folytatni.")
        except Exception as e:
            QMessageBox.critical(self, "Hiba!", f"Hiba történt a mentés folyamán: {str(e)}")

    def show_popup(self):
        msg = QMessageBox()
        msg.setWindowTitle("Hegyvidék teljesítve!")
        msg.setText("Gratulálok a negyedik szint teljesítéséhez!")
        msg.setIcon(QMessageBox.Information)

        x = msg.exec_()

    def opques(self):
        self.queswin = QtWidgets.QMainWindow()
        self.ui = Ui_ques41(self.name, self.total)
        self.ui.setupUi(self.queswin)
        self.queswin.show()
        self.lineEdit.setEnabled(False)
        self.lineEdit_2.setEnabled(False)
        self.lineEdit_3.setEnabled(False)

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    resultwin4 = QtWidgets.QMainWindow()
    ui = Ui_resultwin4()
    ui.setupUi(resultwin4)
    resultwin4.show()
    sys.exit(app.exec_())
