# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\ocsen\PycharmProjects\Szakdoga\pyqt lapok\savewin.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from PyQt5.QtCore import *
import sys
from savename import *

class Ui_savewin(QtWidgets.QWidget):
    def __init__(self, name):
        super().__init__()
        self.name = name
        self.total = 0
    def setupUi(self, savewin):
        savewin.setObjectName("savewin")
        savewin.setEnabled(True)
        savewin.resize(1024, 720)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(savewin.sizePolicy().hasHeightForWidth())
        savewin.setSizePolicy(sizePolicy)
        savewin.setMinimumSize(QtCore.QSize(1024, 720))
        savewin.setMaximumSize(QtCore.QSize(1024, 720))
        self.centralwidget = QtWidgets.QWidget(savewin)
        self.centralwidget.setObjectName("centralwidget")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(0, 0, 1024, 720))
        self.label_5.setMinimumSize(QtCore.QSize(1024, 720))
        self.label_5.setMaximumSize(QtCore.QSize(1024, 720))
        self.label_5.setMouseTracking(False)
        self.label_5.setTabletTracking(False)
        self.label_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("képek/fomenu.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(330, 80, 361, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(430, 160, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.mentesleiras = QtWidgets.QPushButton(self.centralwidget)
        self.mentesleiras.setGeometry(QtCore.QRect(450, 230, 111, 51))
        self.mentesleiras.setStyleSheet("QPushButton{\n"
                                        "    background: rgb(255, 255, 255);\n"
                                        "    border: 2px solid rgb(180, 180, 180);\n"
                                        "    border-radius: 20px;\n"
                                        "}")
        self.mentesleiras.setObjectName("mentesleiras")
        self.esoerdobutton = QtWidgets.QPushButton(self.centralwidget)
        self.esoerdobutton.setGeometry(QtCore.QRect(120, 310, 150, 50))
        self.esoerdobutton.setStyleSheet("QPushButton{\n"
                                        "    background: rgb(255, 255, 255);\n"
                                        "    border: 2px solid rgb(180, 180, 180);\n"
                                        "    border-radius: 20px;\n"
                                        "}")
        self.esoerdobutton.setObjectName("esoerdobutton")
        self.sivatagbutton = QtWidgets.QPushButton(self.centralwidget)
        self.sivatagbutton.setGeometry(QtCore.QRect(120, 370, 150, 50))
        self.sivatagbutton.setStyleSheet("QPushButton{\n"
                                        "    background: rgb(255, 255, 255);\n"
                                        "    border: 2px solid rgb(180, 180, 180);\n"
                                        "    border-radius: 20px;\n"
                                        "}")
        self.sivatagbutton.setObjectName("sivatagbutton")
        self.hegyvidekbutton = QtWidgets.QPushButton(self.centralwidget)
        self.hegyvidekbutton.setGeometry(QtCore.QRect(750, 310, 150, 50))
        self.hegyvidekbutton.setStyleSheet("QPushButton{\n"
                                        "    background: rgb(255, 255, 255);\n"
                                        "    border: 2px solid rgb(180, 180, 180);\n"
                                        "    border-radius: 20px;\n"
                                        "}")
        self.hegyvidekbutton.setObjectName("hegyvidekbutton")
        self.szavannabutton = QtWidgets.QPushButton(self.centralwidget)
        self.szavannabutton.setGeometry(QtCore.QRect(750, 370, 150, 50))
        self.szavannabutton.setStyleSheet("QPushButton{\n"
                                        "    background: rgb(255, 255, 255);\n"
                                        "    border: 2px solid rgb(180, 180, 180);\n"
                                        "    border-radius: 20px;\n"
                                        "}")
        self.szavannabutton.setObjectName("szavannabutton")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(430, 310, 151, 111))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("képek/mentés kép.png"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.T1 = QtWidgets.QLineEdit(self.centralwidget)
        self.T1.setGeometry(QtCore.QRect(110, 100, 150, 50))
        self.T1.setStyleSheet("QLineEdit{\n"
                              "    background: rgb(255, 255, 255);\n"
                              "    border: 2px solid rgb(180, 180, 180);\n"
                              "    border-radius: 20px;\n"
                              "}"
                              "QLineEdit:focus{\n"
                              "border: 2px solid rgb(0, 0, 0);\n"
                              "}"
                              )
        self.T1.setObjectName("T1")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(40, 100, 71, 50))
        self.label_2.setObjectName("label_2")
        savewin.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(savewin)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 21))
        self.menubar.setObjectName("menubar")
        savewin.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(savewin)
        self.statusbar.setObjectName("statusbar")
        savewin.setStatusBar(self.statusbar)

        self.retranslateUi(savewin)
        QtCore.QMetaObject.connectSlotsByName(savewin)

        self.mentesleiras.clicked.connect(self.show_popup)

    def retranslateUi(self, savewin):
        _translate = QtCore.QCoreApplication.translate
        savewin.setWindowTitle(_translate("savewin", "Játékos matematikai gyakorlóprogram"))
        self.label_6.setText(_translate("savewin", "Játékos matematikai gyakorlóprogram"))
        self.label_7.setText(_translate("savewin", "<html><head/><body><p><span style=\" font-size:14pt;\">Mentések betöltése</span></p></body></html>"))
        self.mentesleiras.setText(_translate("savewin", "?"))
        self.esoerdobutton.setText(_translate("savewin", "Esőerdő betöltése"))
        self.sivatagbutton.setText(_translate("savewin", "Sivatag betöltése"))
        self.hegyvidekbutton.setText(_translate("savewin", "Hegyvidék betöltése"))
        self.szavannabutton.setText(_translate("savewin", "Szavanna betöltése"))
        self.label_2.setText(_translate("savewin", "<html><head/><body><p><span style=\" font-size:12pt;\">Becenév:</span></p></body></html>"))
        self.T1.setText(str(self.name))
        self.T1.setEnabled(False)
        self.esoerdobutton.clicked.connect(self.opesoerdo)
        self.esoerdobutton.clicked.connect(savewin.hide)
        self.sivatagbutton.clicked.connect(self.opsivatag)
        self.sivatagbutton.clicked.connect(savewin.hide)
        self.hegyvidekbutton.clicked.connect(self.ophegyvidek)
        self.hegyvidekbutton.clicked.connect(savewin.hide)
        self.szavannabutton.clicked.connect(self.opszavanna)
        self.szavannabutton.clicked.connect(savewin.hide)

    def opesoerdo(self):
        try:
            from ques11 import Ui_ques11
            self.queswin = QtWidgets.QMainWindow()
            self.ui = Ui_ques11(self.name, self.total)
            self.ui.setupUi(self.queswin)
            self.queswin.show()
        except Exception as e:
            print(f"An error occurred: {e}")

    def opsivatag(self):
        try:
            from ques21 import Ui_ques21
            self.queswin = QtWidgets.QMainWindow()
            self.ui = Ui_ques21(self.name, self.total)
            self.ui.setupUi(self.queswin)
            self.queswin.show()
        except Exception as e:
            print(f"An error occurred: {e}")

    def ophegyvidek(self):
        try:
            from ques31 import Ui_ques31
            self.queswin = QtWidgets.QMainWindow()
            self.ui = Ui_ques31(self.name, self.total)
            self.ui.setupUi(self.queswin)
            self.queswin.show()
        except Exception as e:
            print(f"An error occurred: {e}")

    def opszavanna(self):
        try:
            from ques41 import Ui_ques41
            self.queswin = QtWidgets.QMainWindow()
            self.ui = Ui_ques41(self.name, self.total)
            self.ui.setupUi(self.queswin)
            self.queswin.show()
        except Exception as e:
            print(f"An error occurred: {e}")

    def show_popup(self):
        msg = QMessageBox()
        msg.setWindowTitle("Mentés ismertető")
        msg.setText("Ha folytatnád a játékot vagy csak szimplán gyakorolni szeretnél egy adott anyagrészt akkor itt megteheted az adott pálya betöltésével!")
        msg.setIcon(QMessageBox.Information)

        x = msg.exec_()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    savewin = QtWidgets.QMainWindow()
    ui = Ui_savewin()
    ui.setupUi(savewin)
    savewin.show()
    sys.exit(app.exec_())
