# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\ocsen\PycharmProjects\Szakdoga\pyqt lapok\savename.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMessageBox
from homewin import *
from savewin import *

class Ui_savename(object):
    def setupUi(self, savename, homewin):
        self.homewin = homewin
        savename.setObjectName("savename")
        savename.setEnabled(True)
        savename.resize(1024, 720)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(savename.sizePolicy().hasHeightForWidth())
        savename.setSizePolicy(sizePolicy)
        savename.setMinimumSize(QtCore.QSize(1024, 720))
        savename.setMaximumSize(QtCore.QSize(1024, 720))
        self.centralwidget = QtWidgets.QWidget(savename)
        self.centralwidget.setObjectName("centralwidget")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(0, 0, 1024, 720))
        self.label_5.setMinimumSize(QtCore.QSize(1024, 720))
        self.label_5.setMaximumSize(QtCore.QSize(1024, 720))
        self.label_5.setMouseTracking(False)
        self.label_5.setTabletTracking(False)
        self.label_5.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label_5.setText("")
        self.label_5.setPixmap(QtGui.QPixmap("képek/fomenu.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(330, 80, 361, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(430, 160, 161, 61))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.visszabutton = QtWidgets.QPushButton(self.centralwidget)
        self.visszabutton.setGeometry(QtCore.QRect(430, 590, 160, 45))
        self.visszabutton.setStyleSheet("QPushButton{\n"
                                         "    background: rgb(255, 255, 255);\n"
                                         "    border: 2px solid rgb(180, 180, 180);\n"
                                         "    border-radius: 20px;\n"
                                         "}")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("képek/visszanyil.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.visszabutton.setIcon(icon)
        self.visszabutton.setIconSize(QtCore.QSize(25, 25))
        self.visszabutton.setCheckable(False)
        self.visszabutton.setAutoDefault(False)
        self.visszabutton.setDefault(False)
        self.visszabutton.setFlat(False)
        self.visszabutton.setObjectName("visszabutton")
        self.mentesleiras = QtWidgets.QPushButton(self.centralwidget)
        self.mentesleiras.setGeometry(QtCore.QRect(450, 230, 111, 51))
        self.mentesleiras.setStyleSheet("QPushButton{\n"
                                          "    background: rgb(255, 255, 255);\n"
                                          "    border: 2px solid rgb(180, 180, 180);\n"
                                          "    border-radius: 20px;\n"
                                          "}")
        self.mentesleiras.setObjectName("mentesleiras")
        self.B1 = QtWidgets.QPushButton(self.centralwidget)
        self.B1.setGeometry(QtCore.QRect(430, 530, 160, 45))
        self.B1.setStyleSheet("QPushButton{\n"
                                          "    background: rgb(255, 255, 255);\n"
                                          "    border: 2px solid rgb(180, 180, 180);\n"
                                          "    border-radius: 20px;\n"
                                          "}")
        self.B1.setObjectName("B1")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(400, 290, 71, 41))
        self.label.setObjectName("label")
        self.T1 = QtWidgets.QLineEdit(self.centralwidget)
        self.T1.setGeometry(QtCore.QRect(470, 290, 160, 41))
        self.T1.setStyleSheet("QLineEdit{\n"
                              "    background: rgb(255, 255, 255);\n"
                              "    border: 2px solid rgb(180, 180, 180);\n"
                              "    border-radius: 20px;\n"
                              "}"
                              "QLineEdit:focus{\n"
                              "border: 2px solid rgb(0, 0, 0);\n"
                              "}"
                              )
        self.T1.setObjectName("T1")
        savename.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(savename)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1024, 21))
        self.menubar.setObjectName("menubar")
        savename.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(savename)
        self.statusbar.setObjectName("statusbar")
        savename.setStatusBar(self.statusbar)

        self.retranslateUi(savename)
        QtCore.QMetaObject.connectSlotsByName(savename)

        self.mentesleiras.clicked.connect(self.show_popup)

    def retranslateUi(self, savename):
        _translate = QtCore.QCoreApplication.translate
        savename.setWindowTitle(_translate("savename", "Játékos matematikai gyakorlóprogram"))
        self.label_6.setText(_translate("savename", "Játékos matematikai gyakorlóprogram"))
        self.label_7.setText(_translate("savename", "<html><head/><body><p><span style=\" font-size:14pt;\">Mentések betöltése</span></p></body></html>"))
        self.visszabutton.setText(_translate("savename", "Vissza a főmenübe"))
        self.mentesleiras.setText(_translate("savename", "?"))
        self.B1.setText(_translate("savename", "Tovább"))
        self.label.setText(_translate("savename", "<html><head/><body><p><span style=\" font-size:12pt;\">Becenév:</span></p></body></html>"))
        self.visszabutton.clicked.connect(self.ophomewin)
        self.visszabutton.clicked.connect(savename.hide)
        self.B1.clicked.connect(self.opques)
        self.B1.clicked.connect(savename.hide)

    def show_popup(self):
        msg = QMessageBox()
        msg.setWindowTitle("Mentés betöltés")
        msg.setText(
            "Add meg a beceneved a mentés betöltéséhez!")
        msg.setIcon(QMessageBox.Information)

        x = msg.exec_()

    def ophomewin(self):
        #self.homewin = QtWidgets.QMainWindow()
        #self.ui = Ui_homewin()
        #self.ui.setupUi(self.homewin)
        self.homewin.show()

    def opques(self):
        self.S1 = self.T1.text()
        self.queswin = QtWidgets.QMainWindow()
        self.ui = Ui_savewin(self.S1)
        self.ui.setupUi(self.queswin)
        self.queswin.show()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    savename = QtWidgets.QMainWindow()
    ui = Ui_savename()
    ui.setupUi(savename)
    savename.show()
    sys.exit(app.exec_())
